name: FlightResults
options:
  bundleIdPrefix: com.shohanpramanik
  deploymentTarget:
    iOS: "16.0"
configFiles:
  Debug: Config/Config.xcconfig
  Release: Config/Config.xcconfig
fileGroups:
  - Config
targets:
  FlightResults:
    type: application
    platform: iOS
    sources:
      - path: Sources/FlightResults
        excludes:
          - Info.plist
      - path: Fixtures
        type: folder
        buildPhase: resources
      - path: Assets.xcassets
      - path: Fonts
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shohanpramanik.FlightResults
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: Sources/FlightResults/Info.plist
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
schemes:
  FlightResults:
    build:
      targets:
        FlightResults: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
